name: CI devops 2021 EPF
on:
#to begin you want to launch this job in main and develop
  push:
    branches: main
  pull_request:
jobs:
  build-and-test-app:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.3
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      - name: Build and test with Maven
        run: mvn -B package --file simple-api/pom.xml
        
  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: build-and-test-app
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with
          context: ./simple-api
